//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSales.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisements()
        {
            this.Baskets = new HashSet<Baskets>();
        }
    
        public int Id { get; set; }
        public int User { get; set; }
        public int Car { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public decimal Price { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baskets> Baskets { get; set; }
    }
}
