//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSales.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Engines()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int Id { get; set; }
        public int EngineType { get; set; }
        public int Cylinder { get; set; }
        public int Horsepower { get; set; }
        public int Capacity { get; set; }
        public double ConsumptionFuel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual Cylinders Cylinders { get; set; }
        public virtual EngineCapacity EngineCapacity { get; set; }
        public virtual EngineTypes EngineTypes { get; set; }
    }
}
